name: test

on:
  workflow_dispatch:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test_linux:
    name: "linux test: ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, armhf, armv7, amd64, i386]
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
      - name: setup
        run: uv sync --group dev --no-install-project
      - name: build
        run: uv build --wheel
      - name: install
        run: uv pip install dist/*.whl
      - name: test
        run: uv run --no-project pytest -vv tests
  test_macos:
    name: "macos test: ${{ matrix.arch }}"
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
      - name: setup
        run: uv sync --group dev --no-install-project
      - name: build
        run: uv build --wheel
      - name: install
        run: uv pip install dist/*.whl
      - name: test
        run: uv run --no-project pytest -vv tests
  # test_windows:
  #   name: "windows test: ${{ matrix.arch }}"
  #   runs-on: windows-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       arch: [amd64]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: astral-sh/setup-uv@v5
  #     - name: setup
  #       run: uv sync --group dev --no-install-project
  #     - name: build
  #       run: uv build --wheel
  #     - name: install
  #       run: uv pip install dist/*.whl
  #     - name: test
  #       run: uv run --no-project pytest -vv tests
